### ISSUE TITLE
make apidoc error

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-docutils#28] opened 2019-03-25 18:33 UTC
following https://pynwb.readthedocs.io/en/latest/extensions.html#documenting-extensions

tried in https://github.com/bendichter/nwbext_simulation_output/tree/follow_guidelines

```
$ make apidoc
PYTHONPATH=/Users/bendichter/dev/nwbext_simulation_output/docs/source: nwb_generate_format_docs
Output directory already exists: /Users/bendichter/dev/nwbext_simulation_output/docs/source/_format_auto_docs

SORTING TYPES INTO SECTIONS
---------------------------
Traceback (most recent call last):
  File "/Users/bendichter/anaconda3/bin/nwb_generate_format_docs", line 11, in <module>
    load_entry_point('nwb-docutils', 'console_scripts', 'nwb_generate_format_docs')()
  File "/Users/bendichter/dev/nwb-docutils/nwb_docutils/generate_format_docs.py", line 473, in main
    type_sections = DataTypeSection.sort_types_to_sections(default_namespace)
  File "/Users/bendichter/dev/nwb-docutils/nwb_docutils/doctools/renderrst.py", line 78, in sort_types_to_sections
    sections[spec_filename]['data_types'].append(nt)
KeyError: 'nwb.base.yaml'
make: *** [apidoc] Error 1
```

**Comment by oruebel** [comment] 2019-03-25 20:36
I probably won't be able to work on a fix for this today. I think the problem is that the https://github.com/NeurodataWithoutBorders/nwb-docutils/blob/c1e07d9588da2255a761b0b17b8f43f73aadd6ec/nwb_docutils/doctools/renderrst.py#L48 looks only at the main namespace you want to document, i.e., we either need to update the function to ignore types from other namespaces or pass in the ``NamespaceCatalog`` and have it look up the dependent types from the other namespaces. I can try to have a look tomorrow.

**Comment by bendichter** [comment] 2019-03-25 21:00
OK, no rush, I'm just working through an example and making sure all the moving parts interface with each other.

**Comment by oruebel** [comment] 2019-03-25 21:09
It looks like a few bugs have made it into the docutils when I did the refactor. Thanks for testing!

A fitting German word for this is "verschlimmbessern" (i.e., to make something worse through improving it ;-) Although, I think once I fixed these few bugs the docutils will actually be better :-)

**Comment by bendichter** [comment] 2019-03-25 21:16
haha that's a great word! No problem, I'm happy to test.

**Comment by oruebel** [comment] 2019-03-25 23:24
Did you add the ``conf_doc_autogen.py`` and ``conf.py`` in your docs/source folder?

https://github.com/NeurodataWithoutBorders/nwb-schema/blob/dev/docs/format/source/conf_doc_autogen.py
https://github.com/NeurodataWithoutBorders/nwb-schema/blob/dev/docs/format/source/conf.py

The ``conf.py`` script has all the settings for Shinx itself and the  ``conf_doc_autogen.py`` has all the setttings for the ``generate_format_docs.py`` script.

**Comment by bendichter** [comment] 2019-03-26 00:23
I did not add them myself but they were added by `init_sphinx_extension_doc`

**Comment by oruebel** [comment] 2019-03-26 15:50
Makes sense. Can you please add them to the repo. That will make it easier for me to debug the issue. Also, since the setup of the docs will be part of the Git template, I think the init_sphinx_extensions_docs script will probably go away.

**Comment by bendichter** [comment] 2019-03-26 15:53
ok that makes sense. Sure, I'll add them to the repo.

**Comment by bendichter** [comment] 2019-04-24 13:26
Hey @oruebel have you addressed this issue yet?

**Comment by oruebel** [comment] 2019-04-24 15:00
Not yet

**Closed** 2019-05-02 21:27 UTC
Labels: bug
